### ISSUE TITLE
Spec and implement StableHLO Quantization with verifiers

### ISSUE THREAD

**Issue by abhigunj** [openxla/stablehlo#2173]
Parent ticket to track any open/ new quantization verifier tasks

```[tasklist]
### Tasks
- [ ] https://github.com/openxla/stablehlo/issues/2074
- [ ] https://github.com/openxla/stablehlo/issues/2145
- [x] Update the status.md to reflect that type inference for quantized operations are mostly infeasible.
```

**Comment by sdasgup3** [comment]
@abhigunj Can we close this?
