### ISSUE TITLE
StableHLO Opset Deprecations Tracker

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#2340]
### Request description

Tracker issue for opset deprecations proposed in [StableHLO v1.0 Opset Cleanups](https://github.com/openxla/stablehlo/blob/main/rfcs/20240503-opset-deprecations.md):

- [ ] Delete CreateTokenOp and TraceOp
- [ ] Deprecate BroadcastOp, DotOp, UnaryEinsumOp
- [ ] Deprecate RealDynamicSliceOp, Enhance DynamicSliceOp
- [ ] Deprecate MapOp, RngOp, EinsumOp TorchIndexSelectOp, Tuple support, complex comparisons

**Comment by GleasonK** [comment]
Updates:

-  `TraceOp` has been removed.
- `CreateTokenOp` should be cleaned up shortly.
- `UnaryEisumOp` was removed from XLA and can be removed from StableHLO at any time.
- `BroadcastOp` and `DotOp` migration to begin shortly, new methods added to dot_general and broadcast_in_dim for checking equivalence to the deprecated op.
